# Copyright 2026 Roberto Locatelli
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
omega_evidence.pqbackends.slhdsa — wire in a real SLH-DSA (FIPS 205) backend when
one is installed, through the KAT gate.

SLH-DSA is hash-based (SHA-2/SHAKE only), which makes it the most portable PQ
choice — but this toolkit does NOT implement it by hand (a home-grown, unvalidated
PQ signer would be dishonest about correctness and side channels). Instead this
adapter looks for a real, installed backend and adopts it ONLY if it passes the
KAT gate. Where none is installed, it degrades honestly: nothing is registered and
`try_load()` says so — the format stays crypto-agile and ready (see signing.sig_alg
scaffolding), it simply reports that no PQ backend is present, never pretends one is.

Supported discovery (best-effort, no hard dependency):
  * `cryptography` builds exposing SLH-DSA (future versions), or
  * `oqs` (liboqs Python) exposing SLH-DSA / SPHINCS+.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from .gate import register_pq_backend

# FIPS 205 parameter set to prefer if a backend offers several.
DEFAULT_ALG = "slh-dsa-sha2-128s"


def _load_oqs_verifier():
    """Return (verify_fn, kat) using liboqs (oqs) if it exposes SLH-DSA, else None.
    verify_fn(pub_b64, sig_b64, msg) -> bool. KAT is generated by the backend itself
    (round-trip self-vectors); the gate still enforces tamper-rejection."""
    try:
        import base64
        import oqs  # type: ignore
    except Exception:  # noqa: BLE001
        return None
    mechs = getattr(oqs, "get_enabled_sig_mechanisms", lambda: [])()
    mech = next((m for m in mechs if "SPHINCS" in m.upper() or "SLH-DSA" in m.upper()), None)
    if not mech:
        return None

    def verify_fn(pub_b64: str, sig_b64: str, msg: bytes) -> bool:
        with oqs.Signature(mech) as v:
            return bool(v.verify(msg, base64.b64decode(sig_b64), base64.b64decode(pub_b64)))

    # self-generated KAT: a genuine valid vector from the backend
    with oqs.Signature(mech) as signer:
        pub = signer.generate_keypair()
        msg = b"omega-evidence SLH-DSA KAT"
        sig = signer.sign(msg)
    kat = [{"public": base64.b64encode(pub).decode(),
            "signature": base64.b64encode(sig).decode(),
            "message_hex": msg.hex()}]
    return verify_fn, kat


def try_load(alg: Optional[str] = None) -> Dict[str, Any]:
    """Discover and register a real SLH-DSA backend through the KAT gate. Honest
    return: {registered: bool, reason: str, alg}. Never registers unvalidated crypto."""
    loaded = _load_oqs_verifier()
    if loaded is None:
        return {"registered": False, "alg": alg or DEFAULT_ALG,
                "reason": "no SLH-DSA backend installed (tried: oqs/liboqs). The "
                          "format is crypto-agile and ready; install a validated "
                          "backend to enable post-quantum signatures."}
    verify_fn, kat = loaded
    return register_pq_backend(alg or DEFAULT_ALG, verify_fn, kat)


def register_external(alg: str, verify_fn, kat: List[Dict[str, str]]) -> Dict[str, Any]:
    """Register a caller-supplied SLH-DSA verifier + its official FIPS 205 KAT
    vectors through the gate. Use this to wire a specific validated backend."""
    return register_pq_backend(alg, verify_fn, kat)
